version: '2.4'
services:
  ors-app:
    container_name: ors-app
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:9001:9001
    image: gcr.io/taas-356118/openrouteservice/openrouteservice:v2
    build:
      context: ../
      args:
        ORS_CONFIG: ./docker/conf/ors-config.json
        OSM_FILE: ./docker/california-latest.osm.pbf
        ORS_GRAPHS: ./docker/graphs
        ORS_CACHE: ./docker/elevation_cache
#    user: "${ORS_UID:-0}:${ORS_GID:-0}"
#    volumes:
#      - ${PWD}/graphs:/ors-core/data/graphs
#      - ${PWD}/elevation_cache:/ors-core/data/elevation_cache
#      - ${PWD}/logs/ors:/var/log/ors
#      - ${PWD}/logs/tomcat:/usr/local/tomcat/logs
#      - ${PWD}/conf:/ors-conf
#      - ${PWD}/california-latest.osm.pbf:/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx5g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
